### ISSUE TITLE
/quit cliente com error pthread_cancel

### ISSUE THREAD

**Issue by Math-O5** [Math-O5/internal-relay-chat#8]
[Switching to Thread 0x7ffff7250700 (LWP 21640)]
0x00007ffff7c2ca64 in pthread_cancel () from /lib64/libpthread.so.0
Missing separate debuginfos, use: dnf debuginfo-install libgcc-9.2.1-1.fc30.x86_64 libstdc++-9.2.1-1.fc30.x86_64

**Comment by GabrielVanLoon** [comment]
Tá resolvido chefia!!!
